#!/usr/bin/env bash

# Script that checks on the domain

print_my_domain () {
           dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    print_my_domain "$2.$1" "$2"
else
    print_my_domain "www.$1" "www"
    print_my_domain "lb-01.$1" "lb-01"
    print_my_domain "web-01.$1" "web-01"
    print_my_domain "web-02.$1" "web-02"
fi
