#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
#sudo sed -i 's/server_name _;.*/server_name _;\n\tadd_header X-Served-By \$hostname;/' /etc/nginx/sites-enabled/default 
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello world!" | sudo tee /var/www/html/index.html

# create a redirection
new_strings="server_name _;\n\trwite\ ^\redirect_me\https:\/\/github.com\/Festongithub permanent";
sudo sed -i "new_strings s/server _name _;/$new_string/" /etc/nginx/sites-enabled-enabled/default;
# create custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
# custom nginx

sudo sed -i "/server _name _/a add_header X-served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
# check syntax errors
sudo nginx -t
# restart

sudo service nginx restart
