#!/bin/bash

# create a user named nginx if it doesn't exist already
if ! id -u nginx >/dev/null 2>&1; then
    useradd -r -s /sbin/nologin nginx
fi

# backup the existing nginx configuration file
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

# replace the nginx configuration with a new configuration
cat > /etc/nginx/nginx.conf << EOF
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    log_format  main  '\$remote_addr - \$remote_user [\$time_local] "\$request" '
                      '\$status \$body_bytes_sent "\$http_referer" '
                      '"\$http_user_agent" "\$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    sendfile on;
    keepalive_timeout 65;
    server {
        listen 8080 default_server;
        listen [::]:8080 default_server;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;
        location / {
            try_files \$uri \$uri/ =404;
        }
    }
}
EOF

# restart nginx service
systemctl restart nginx.service

